image: python:3.7

before_script:
  - pip install tox

stages:
- Install
- Static
- Test
- Docs

install:
  stage: Install
  script:
    - pip install .

codestyle:
  stage: Static
  script:
    - tox -e codestyle

twine:
  stage: Static
  script:
    - tox -e twine

py37-online:
  stage: Test
  script:
    - tox -e py37-online

py38-online:
  stage: Test
  image: python:3.8
  script:
    - tox -e py38-online

py37-devdeps:
  allow_failure: true
  stage: Test
  script:
    - tox -e py37-devdeps

build_docs:
  stage: Docs
  script:
    - tox -e build_docs
