repos:
  # - repo: https://github.com/PyCQA/docformatter
  #   rev: 7798699c0a9ddcc41a16b4dd7b8e216443f78792
  #   hooks:
  #     - id: docformatter
  #       args: ["-r", "--in-place", "--pre-summary-newline", "--make-summary-multi", "--black"]
    # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.5"
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
      - id: ruff-format
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|extern.*|irispy/extern)$"
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.11.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/tox-dev/tox-toml-fmt
    rev: v1.2.1
    hooks:
      - id: tox-toml-fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=5682"]
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|.json)$|^CITATION.rst$"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*)$"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [ "--write-changes" ]
ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
